# Generated by Django 5.0.1 on 2024-01-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0021_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviekid',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
